server:
  port: 8088

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501     # 超时时间
  connect-timeout: 601   # 连接超时时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
#    - 192.168.200.128:22122
    - 39.108.62.120:22122
#    - 192.168.0.105:22122


